### ISSUE TITLE
Add/Update project on LFX - OpenSTEF

### ISSUE THREAD

**Issue by FrankKr** [lf-energy/foundation#10]
Please add the project OpenSTEF to the LFX.

Thank you!

**Comment by jmertic** [comment]
This is in queue, but we are blocked on adding new projects until June. Closing for now.

**Comment by FrankKr** [comment]
@jmertic June has come and gone, any chance on including OpenSTEF to LFX?
We are scheduled next week for the yearly review and I would like to include the LFX insights dashboard if that is possible. Thanks!

**Comment by jmertic** [comment]
Yep! It's added in Insights v2 at https://insights-v2.lfx.linuxfoundation.org/openstf/trends
