### ISSUE TITLE
Logo request OpenSTEF

### ISSUE THREAD

**Issue by FrankKr** [lf-energy/foundation#11]
Hi! I would like to request the creation of a logo for the OpenSTEF project.

It is mentioned as a step on the 'project intake checklist', but since I can't find a template issue, I'm posting it like this.
![image](https://user-images.githubusercontent.com/18208480/145563577-2c33a17b-237e-4d77-808a-3e6f2d415860.png)

Could you let me know if this is the correct place to make such a request, and also which information I need to provide?
Thanks!

**Comment by jmertic** [comment]
Yes - can you complete the creative brief at https://forms.gle/M8V7ufSdNSHHRdaL7
