### ISSUE TITLE
Transfer domain flexmeasures.io

### ISSUE THREAD

**Issue by nhoening** [lf-energy/foundation#13]
The domain https://flexmeasures.io can now become owned by LF Energy.

**Comment by jmertic** [comment]
Hi @nhoening - can you open the ticket at https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63? This will ensure all the right information needed is provided. Thanks!

**Comment by nhoening** [comment]
Done, see https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-23756

**Comment by jmertic** [comment]
Awesome - thank you!
