### ISSUE TITLE
New Slack Channel - [CHANNEL]

### ISSUE THREAD

**Issue by lucian-balea** [lf-energy/foundation#6]
Please complete all the sections below to request a new channel. Channel requests can take a day or two, so please be patient :-).

# Channel name
seapath

# Channel purpose
SEAPATH project channel.

# Moderators for the channel
aurelien.watare@rte-france.com
robin.massink@alliander.com

**Comment by LindsayLF** [comment]
Hi @lucian-balea - The slack channel has been created within the LFE Slack Workspace: lfenergy.slack.com.  Additionally, I've invited Aurelien and Robin to the workspace, once they accept we can make them admins.  Thank you!

**Comment by LindsayLF** [comment]
Slack channel has been created and Aurelien and Robin has access to manage channel.
