### ISSUE TITLE
 New Mailing List - OpenSTEF

### ISSUE THREAD

**Issue by FrankKr** [lf-energy/foundation#9]
Please complete all the sections below to request a new mailing list. Requests can take a day or two, so please be patient :-).

# Project name
OpenSTEF

# Would you like a combined -user and -dev list, or separate
combined

# Moderators/owner(s) for the mailing list
me please; fpmkreuwel@gmail.com / FrankKr (github account)

# Does this channel have a lifespan? ( if so, please let us know when that is so we can archive it or mark it inactive )
no

Thank you!

**Comment by Jonasvdbo** [comment]
@FrankKr There are already two mailing lists created for OpenSTEF:
-  openstef@lists.lfenergy.org -> https://lists.lfenergy.org/g/openstef
- openstef-tsc@lists.lfenergy.org -> https://lists.lfenergy.org/g/openstef-tsc

Please check if these two are sufficient for you and you can access them als owner / moderator.

**Comment by FrankKr** [comment]
OK, great, thanks for pointing those out!
